Chore: Re-instate action to submit PR in workflow [skip ci]
Signed-off-by: Matthew Watkins <mwatkins@linuxfoundation.org>

diff --git a/.github/workflows/bootstrap.yaml b/.github/workflows/bootstrap.yaml
--- a/.github/workflows/bootstrap.yaml
+++ b/.github/workflows/bootstrap.yaml
@@ -89,7 +89,7 @@ jobs:
               fi
               # Update folder contents
               echo "Updating folder contents: $FOLDER"
-              for FILE in $(find .devops/"$FOLDER" -type f); do
+              for FILE in $(find .devops/"$FOLDER" -maxdepth 0 -type f); do
                 echo "Copying: $FILE into $FOLDER"
                 cp "$FILE" "$FOLDER"
               done
@@ -117,16 +117,37 @@ jobs:
             # Set a flag for use by the next action/step
             echo "changed=true" >> "$GITHUB_OUTPUT"
           fi
-          git add .
-          if ! (git commit -as -S -m "Chore: Update DevOps tooling from central repository [skip-ci]" \
-            -m "This commit created by automation/scripting" --no-verify); then
-            echo "Commit failed; aborting"; exit 1
+          if [ -n "$GITHUB_TOKEN" ]; then
+            git add .
+            if ! (git commit -as -S -m "Chore: Update DevOps tooling from central repository [skip-ci]" \
+              -m "This commit created by automation/scripting" --no-verify); then
+              echo "Commit failed; aborting"; exit 1
+            else
+              git push --set-upstream origin update-devops-tooling
+              # ToDo: need to verify if we are running in a GHA
+              gh pr create --title \
+                "Chore: Pull DevOps tooling from upstream repository" \
+                --body 'Automated by a GitHub workflow: bootstrap.yaml'
+            fi
           else
-            git push --set-upstream origin update-devops-tooling
-            # ToDo: need to verify if we are running in a GHA
-            gh pr create --title \
-              "Chore: Pull DevOps tooling from upstream repository" \
-              --body 'Automated by a GitHub workflow: bootstrap.yaml'
+            echo "Script running in GitHub Actions workflow; proceeding to next step"
           fi
-
           ### SHELL CODE END ###
+
+      - name: Create Pull Request
+        if: steps.update-repository.outputs.changed == 'true'
+        uses: peter-evans/create-pull-request@v6
+        env:
+          GITHUB_TOKEN: ${{ github.token }}
+        with:
+          token: ${{ github.token }}
+          commit-message: "Chore: Update DevOps tooling from central repository [skip-ci]"
+          signoff: "true"
+          branch: devops-update
+          delete-branch: true
+          title: "Chore: Update DevOps tooling from central repository [skip-ci]"
+          body: |
+            Update repository with content from upstream: os-climate/devops-toolkit
+          labels: |
+            automated pr
+          draft: false
